### ISSUE TITLE
Perhaps add the exact section - 6.2.3

### ISSUE THREAD

**Issue by arielgabizon** [KZen-networks/zk-paillier#5]
https://github.com/KZen-networks/zk-paillier/blob/635e1963cdfe84a873ba97b8bb81da580f947420/src/zkproofs/correct_key_ni.rs#L24

Also, somewhere it should be mentioned that they implicitly use gcd(n,phi(n))>1 ==> raising to power n is not a permutation on Z_n

**Comment by omershlo** [comment]
done. 
About your comment: I think it should be mentioned in the paper, not the code... perhaps forward this comment to the authors ?

**Comment by arielgabizon** [comment]
Yeah.. don't know if it's worth writing an email..what's convenient about github is you can easily point out this stuff :)
